name: Code Quality Checks

on: [push]

jobs:
  black:
    name: 'Check code quality with black'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
      - name: Check formatting
        run: |
          black src --check
  flake:
    name: 'Check code health with Flake8'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cclauss/GitHub-Action-for-Flake8@0.0.1
        with:
          args: "flake8 src --max-line-length=120"
  pylint:
    name: 'Check code quality with pylint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pylint
      - name: Lint
        run: |
          pylint --exit-zero src