on: 
  push:
  schedule:
    - cron: '0 0 1 1-12 *'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run script
        run: |
          python src/main.py
      - name: Zip
        run: |
          zip documents/pdfs/csvs.zip ./documents/pdfs/*.csv
      - name: Get current date and timestamp
        id: timestamp
        run: | 
          echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H:%M')"
          echo "::set-output name=timestamptag::$(date +'%Y-%m-%d-%H-%M')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: "${{ steps.timestamp.outputs.timestamptag }}"
          release_name: "CSVs on ${{ steps.timestamp.outputs.timestamp }}"
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./documents/pdfs/csvs.zip
          asset_name: csvs.zip
          asset_content_type: application/zip